### ISSUE TITLE
Caret for merge bloc doesn't follow the bloc border color

### ISSUE THREAD

**Issue by vulcaryn** [Brettm12345/github-moonlight#66]
**Describe the bug:**
The caret of merge bloc has the wrong color.

**Expected behavior:**
The caret should follow the bloc border color.

**Where did this happen:**
Any page containing merge bloc ex: https://github.com/Brettm12345/github-moonlight/pull/65

**Screenshots:**
![Sans titre](https://user-images.githubusercontent.com/5725953/100997184-47a11580-355a-11eb-821b-17aa484e6c99.png)

**Desktop (please complete the following information):**
 - OS: MacOS 11.0.1
 - Browser: Firefox Nightly
 - Version: 85

 **Additional add-ons installed:**
JetBrains toolbox extension

**Comment by ryokohbato** [comment]
This issue seems to have already been fixed in PR #63.
I hope a new version will be released, but you can also manually import the current latest master branch into Stylus. Open the latest [github.user.css](https://github.com/Brettm12345/github-moonlight/blob/master/github.user.css) and display `Raw`.
